### ISSUE TITLE
Theme has unconfigurable template "Footer Content"

### ISSUE THREAD

**Issue by mitchhentges** [Xzya/hugo-material-blog#2]
Thanks for the sharp theme! It looks great so far :100: :tada:

When this theme is used, the "Footer Content" is always:

> You can use rows and columns here to organize your footer content.

You can even see this on the [example site](https://themes.gohugo.io/theme/hugo-material-blog/).

**Comment by Xzya** [comment]
Hello,

The footer content can be overwritten by creating the `footer-content.html` partial in your site.
I was first thinking of adding it to the config, however, having it in a separate partial allows you for more control (e.g. you can modify the structure to fit your needs).

Take a look [here](https://github.com/Xzya/hugo-material-blog/blob/master/exampleSite/layouts/partials/footer-content.html) at the partial the `exampleSite` is using.

Let me know if you have any questions,
Thank you!

PS: @mitchhentges thank you for your support!

**Comment by mitchhentges** [comment]
Okay, that makes sense, thanks!
