### ISSUE TITLE
Update Materialize to version 1.0.0

### ISSUE THREAD

**Issue by dgrammlich** [Xzya/hugo-material-blog#4]
Hi Mihail,

at first thank you for your Hugo blog theme. I really like its clean design.

I've tried to update Materialize to version 1.0.0, but I'm a total CSS and JavaScript noob... I couldn't get the sidenav and the dropdown to work. Maybe you like to jump in and help me? =)

Best
Dani

**Comment by dgrammlich** [comment]
I've created a pull request with my changes so far. See #5.

**Comment by Xzya** [comment]
Hello,

Thank you for you pull request! Everything seems to work fine with your PR (including sidenav and dropdowns).

Is there something else you need help with?

Thank you!

**Comment by dgrammlich** [comment]
Hi Mihail,

thanks for your offer! I migrated my webside once again and everything works fine. Maybe I was code blind during my last try and couldn't see my mistake, I don't know...

I'm happy that I was able to contribute to your beautiful theme.

Best
Dani
